spring:
  cache:
    type: redis
    redis:
      time-to-live: 1h
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.10.1.52:1521/POSPRDDB.arvind.local
    username: pos
    password: PoS2019
    
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
query:
  getLocations: 
    fetch: 
      'SELECT ASH.ORGANIZATION_ID, ASH.LEVEL_CODE, ASH.LEVEL_VALUE, LRL.RTL_LOC_ID, ASH.COMPANY_NAME,
      ASH.DISTRIBUTION_CHANNEL, ASH.CIN_NO, ASH.SUPER_BUILT_UP_AREA,
      ASH.BUSINESS_MODEL, ASH.CUSTOMER_FOLIO, ASH.CUSTOMER_GROUP, ASH.ATTRIBUTE_2, ASH.DIVISION_EXTENDED_FOR_CUSTOMER, ASH.SAP_CODE_CREATION, ASH.CARPET_AREA,
      ASH.GRADING_DETAILS, ASH.BRAND_DIVISION_ATTRIBUTE, ASH.TAX_GROUP, ASH.REGION_BASED_ON_USERS, ASH.PARENT_STORE_CODE, ASH.STORE_STATUS, ASH.STORE_TYPE, ASH.STORE_FORMAT, ASH.GSTN, BR.DESCRIPTION BRAND,
      LRL.STORE_NAME, LRL.ADDRESS1, LRL.ADDRESS2, LRL.ADDRESS3, LRL.ADDRESS4, LRL.TELEPHONE1, LRL.CITY, LRL.STATE, LRL.POSTAL_CODE, ASH.STORE_EMAIL, ASH.ATTRIBUTE_6, ASH.BRAND PRIMARY_BRAND
      FROM ARV_STORE_HIERARCHY ASH, LOC_RTL_LOC LRL, DTV.ARV_STORE_BRAND_MAPPING BR WHERE ASH.ORGANIZATION_ID = LRL.ORGANIZATION_ID AND ASH.CUSTOMER_SITE_CODE = LRL.RTL_LOC_ID AND ASH.CUSTOMER_SITE_CODE=BR.RTL_LOC_ID  '
    filter:
      storeId: ' AND (ASH.CUSTOMER_SITE_CODE IN (:storeId) OR ASH.PARENT_STORE_CODE IN (:storeId)) '
      region: ' AND UPPER(ASH.ATTRIBUTE_2) IN (:region) '
      brand: ' AND UPPER(BR.DESCRIPTION) IN (:brand) '
      channel: ' AND UPPER(ASH.DISTRIBUTION_CHANNEL) IN (:channel) '
      state: ' AND UPPER(ASH.TAX_GROUP) IN (:state) '
      city: ' AND UPPER(ASH.REGION_BASED_ON_USERS) IN (:city) '
  getLocationStatus: 
    fetch: 
      SELECT DISTINCT STRING_VALUE FROM DTV.LOC_STATE_JOURNAL WHERE  STATUS_TYPCODE IN ('RTL_LOC_STATE', 'WKSTN_STATE') AND STRING_VALUE = 'OPEN' AND TRUNC(TIME_STAMP) = TRUNC(SYSDATE) AND WKSTN_ID = 1
    filter:
      storeId: ' AND (RTL_LOC_ID IN (:storeId)) '
